---
title: codeR
output: 
  html_document:
    df_print: paged
    includes:
      in_header: header.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)

# packages

# iNZight
library(iNZightPlots)

# core tidyverse
library(ggplot2)
library(tibble)
library(tidyr)
library(dplyr)
library(readr)
library(stringr)
library(purrr)
library(forcats)

# other tidyverse
library(httr)
library(magrittr)
library(readxl)
library(rvest)
library(jsonlite)
library(xml2)
library(glue)
library(lubridate)
library(knitr)

# favourites
library(magick)
library(htmltools)

# others
library(gtrendsR)
library(ggimage)

# mine from github
#devtools::install_github("annafergusson/udsdata")
library(udsdata)


# settings
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8, fig.height = 4)
tutorial_options(exercise.timelimit = 90)

# I think the stuff below means the previous code is not cached but ???
options(tutorial.storage = list(
  # save an arbitrary R object "data" to storage
   save_object = function(tutorial_id, tutorial_version, user_id, object_id, data) {},
  # retreive a single R object from storage
  get_object = function(tutorial_id, tutorial_version, user_id, object_id) { 
    NULL 
  },
  
  # retreive a list of all R objects stored
  get_objects = function(tutorial_id, tutorial_version, user_id) { 
    list() 
  },
  
  # remove all stored R objects
  remove_all_objects = function(tutorial_id, tutorial_version, user_id) {
  }
))

# hack to get iNZight plots to show
showPlot <- function(inzy, width = 800, height = 400){
  plot <- magick::image_graph(width = width, height = height)
  inzy
  dev.off()
  plot[length(plot)] #show the last layer
}

# function to get data out and into iNZightLite
iNZightLink <- function(data) {
  json_output <- jsonlite::toJSON(data)
  anna_url <- "https://csv.monster/tempcsv.php"
  response <- httr::POST(url = anna_url, body = list(t = json_output))
  temp_csv_url <- httr::content(response, "text")
  src <- paste0("https://lite.docker.stat.auckland.ac.nz/?url=", temp_csv_url, "&land=visualize")
  data.frame(link_to_iNZight_lite = paste0("<a href='", src, "' target = '_blank'>", src, "</a>")) %>% kable()
}
```

```{css}
    /* Absolute Center Spinner */
.loading {
  z-index: 999;
  overflow: show;
  margin: auto;
  display: block;
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(0,0,0,0.3);
}

.title{
display:none;
}

#refresh_code{
display:none;
}

img{
  width:100%;
}

.code-exercise {
  display:none;
}
```

<div id="loader"></div>

```{r refresh-button}
htmltools::tags$button("Get code", 
                       id = 'refresh_code')
```

```{r live-code, exercise=TRUE}

```

```{js}
$().ready(function(){
  updateEditor();
  var urlParams = new URLSearchParams(window.location.search);
  if(urlParams.has('code'))
  {
    var code = urlParams.get('code');
    code = decodeURI(code);
    if(code !== "")
    {
        document.getElementById('section-loader').className = 'loading';
      fetch(code, {mode: 'cors'})
      .then(function(response) {
        return response.text();
      })
      .then(function(new_code) {
        var editor = ace.edit("tutorial-exercise-live-code-code-editor");
        editor.setValue(new_code);
        var line_last = editor.session.getLength();
        editor.gotoLine(line_last);
        editor.setOptions({maxLines: Infinity});
        document.getElementById('section-loader').className = '';
        $(".code-exercise").show();
      });
    }
    else
    {
      document.getElementById('section-loader').className = '';
      $(".code-exercise").show();
    }
  }

if(urlParams.has('raw'))
  {
    var code = urlParams.get('raw');
    code = decodeURI(code);
    if(code !== "")
    {
        document.getElementById('section-loader').className = 'loading';
        var editor = ace.edit("tutorial-exercise-live-code-code-editor");
        editor.setValue(code);
        var line_last = editor.session.getLength();
        editor.gotoLine(line_last);
        editor.setOptions({maxLines: Infinity});
        document.getElementById('section-loader').className = '';
        $(".code-exercise").show();
    }
    else
    {
      document.getElementById('section-loader').className = '';
      $(".code-exercise").show();
    }
  }
  
  //hide "get code" button if there is no live code to pull in
  if(urlParams.has('db_link'))
    {
      $("#refresh_code").show();
    }
    else
    {
      $("#refresh_code").hide();
    }
  
  //add refresh_code function to button
  $("#refresh_code").click(function(){
    document.getElementById('section-loader').className = 'loading';
    var urlParams = new URLSearchParams(window.location.search);
    if(urlParams.has('db_link'))
    {
      var db_link = urlParams.get('db_link');
      db_link = decodeURI(db_link);
      if(db_link !== "")
       {
        fetch(db_link, {mode: 'cors'})
        .then(function(response) {
        return response.text();
      })
      .then(function(new_code) {
        var editor = ace.edit("tutorial-exercise-live-code-code-editor");
        editor.setValue(new_code);
        var line_last = editor.session.getLength();
        editor.gotoLine(line_last);
        editor.setOptions({maxLines: Infinity});
        document.getElementById('section-loader').className = '';
        $(".code-exercise").show();
      });
    }
    else
    {
      document.getElementById('section-loader').className = '';
      $(".code-exercise").show();
    }
    }
  });
});

function updateEditor(){
  //extra ace editor changes
  var new_id = "tutorial-exercise-live-code-code-editor";
  var editor = ace.edit(new_id);
  editor.getSession().setUseWrapMode(true);
  editor.setFontSize("14px");
  editor.setOptions({maxLines: Infinity});
  document.getElementById("tutorial-exercise-live-code-output").innerHTML = "";
}

```

```{js}
  (function() {
    var link = document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = 'www/udc_fav.png';
    document.getElementsByTagName('head')[0].appendChild(link);
})();
```